---
- name: Clone dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ target_home }}/.dotfiles"
    version: HEAD
    update: false
  when: dotfiles_repo is defined

- name: Populate SSH authorized_keys from dotfiles
  ansible.posix.authorized_key:
    user: "{{ target_user }}"
    key: "{{ lookup('file', target_home + '/.dotfiles/' + ssh_authorized_keys_dotfile) }}"
    state: present
  when: ssh_authorized_keys_dotfile is defined and ssh_authorized_keys_dotfile | length > 0

- name: Symlink dotfiles
  ansible.builtin.file:
    src: "{{ target_home }}/.dotfiles/{{ item.src }}"
    dest: "{{ target_home }}/{{ item.dest }}"
    state: link
  loop:
    - src: gitconfig
      dest: .gitconfig
    - src: gitignore_global
      dest: .gitignore_global
    - src: tmux.conf
      dest: .tmux.conf
  when: dotfiles_repo is defined
