---
- name: Build mbpfan into the local AUR repository
  ansible.builtin.command: "{{ aur_sync_command }} mbpfan"
  environment: "{{ aur_build_environment }}"
  register: _aur_sync_mbpfan
  changed_when: "'there is nothing to do' not in _aur_sync_mbpfan.stderr"
  become: true
  become_user: "{{ target_user }}"

- name: Install mbpfan
  community.general.pacman:
    name: mbpfan
    state: present
    update_cache: "{{ _aur_sync_mbpfan.changed }}"

- name: Install mbpfan service override
  ansible.builtin.copy:
    src: /usr/lib/systemd/system/mbpfan.service
    dest: /etc/systemd/system/mbpfan.service
    remote_src: true
    mode: '0644'

- name: Enable mbpfan
  ansible.builtin.systemd:
    name: mbpfan
    enabled: true
    state: started
    daemon_reload: true
