---
- name: Enable thinkpad_acpi fan control
  # Required for thinkfan to write to /proc/acpi/ibm/fan.
  ansible.builtin.copy:
    dest: /etc/modprobe.d/gatherd-thinkpad_acpi.conf
    content: "options thinkpad_acpi fan_control=1\n"
    mode: '0644'
  notify: Etckeeper commit

- name: Configure thinkfan
  ansible.builtin.template:
    src: thinkfan.conf.j2
    dest: /etc/thinkfan.conf
    mode: '0644'
  notify: Etckeeper commit
