---
- name: Install slow x86-only packages
  community.general.pacman:
    name: "{{ rest_slow_x86_packages }}"
    state: present
  when: not is_aarch64

- name: Install slow packages
  community.general.pacman:
    name: "{{ rest_slow_packages }}"
    state: present
  retries: 3
  delay: 10
  register: _slow_pkg_install
  until: _slow_pkg_install is succeeded
