#!/bin/sh
# XDG_CURRENT_DESKTOP=GNOME is required for 1Password's browser integration under Sway.
pgrep -f '1password --silent' >/dev/null && exit 0
exec env XDG_CURRENT_DESKTOP=GNOME 1password --silent
