---
- name: Etckeeper commit
  ansible.builtin.command: "etckeeper commit -m 'Ansible: converge system configuration.'"
  changed_when: false
  failed_when: false

- name: Reload logind
  ansible.builtin.systemd:
    name: systemd-logind
    state: restarted

- name: Reload udev
  ansible.builtin.shell: |
    udevadm control --reload-rules
    udevadm trigger --action=add --subsystem-match=input
  changed_when: false

- name: Reload firewall
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false

- name: Reload NetworkManager connections
  ansible.builtin.command: nmcli connection reload
  changed_when: false

- name: Reload autofs
  ansible.builtin.systemd:
    name: autofs
    state: reloaded
  failed_when: false

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
